services:
  observer:
    image: roeldev/youless-observer:local
    build:
      context: .
      args:
        APP: observer
    user: nonroot
    env_file:
      - ./cmd/observer/.env
      - ./cmd/observer/.env.docker.local
    ports:
      - "2512:2512"
