// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/v1/apiv1.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeterReadingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MeterReadingRequest) Reset() {
	*x = MeterReadingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeterReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingRequest) ProtoMessage() {}

func (x *MeterReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingRequest.ProtoReflect.Descriptor instead.
func (*MeterReadingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{0}
}

type MeterReadingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Electricity *MeterReadingResponse_Electricity `protobuf:"bytes,1,opt,name=electricity,proto3,oneof" json:"electricity,omitempty"`
	S0          *MeterReadingResponse_S0          `protobuf:"bytes,2,opt,name=s0,proto3,oneof" json:"s0,omitempty"`
	Gas         *MeterReadingResponse_Value       `protobuf:"bytes,3,opt,name=gas,proto3,oneof" json:"gas,omitempty"`
	Water       *MeterReadingResponse_Value       `protobuf:"bytes,4,opt,name=water,proto3,oneof" json:"water,omitempty"`
}

func (x *MeterReadingResponse) Reset() {
	*x = MeterReadingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeterReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingResponse) ProtoMessage() {}

func (x *MeterReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingResponse.ProtoReflect.Descriptor instead.
func (*MeterReadingResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1}
}

func (x *MeterReadingResponse) GetElectricity() *MeterReadingResponse_Electricity {
	if x != nil {
		return x.Electricity
	}
	return nil
}

func (x *MeterReadingResponse) GetS0() *MeterReadingResponse_S0 {
	if x != nil {
		return x.S0
	}
	return nil
}

func (x *MeterReadingResponse) GetGas() *MeterReadingResponse_Value {
	if x != nil {
		return x.Gas
	}
	return nil
}

func (x *MeterReadingResponse) GetWater() *MeterReadingResponse_Value {
	if x != nil {
		return x.Water
	}
	return nil
}

type PhaseReadingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PhaseReadingRequest) Reset() {
	*x = PhaseReadingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseReadingRequest) ProtoMessage() {}

func (x *PhaseReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseReadingRequest.ProtoReflect.Descriptor instead.
func (*PhaseReadingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{2}
}

type PhaseReadingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariff uint32                        `protobuf:"varint,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
	Phase  []*PhaseReadingResponse_Phase `protobuf:"bytes,2,rep,name=phase,proto3" json:"phase,omitempty"`
}

func (x *PhaseReadingResponse) Reset() {
	*x = PhaseReadingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseReadingResponse) ProtoMessage() {}

func (x *PhaseReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseReadingResponse.ProtoReflect.Descriptor instead.
func (*PhaseReadingResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{3}
}

func (x *PhaseReadingResponse) GetTariff() uint32 {
	if x != nil {
		return x.Tariff
	}
	return 0
}

func (x *PhaseReadingResponse) GetPhase() []*PhaseReadingResponse_Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type MeterReadingResponse_Electricity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Import1   float64                `protobuf:"fixed64,2,opt,name=import1,proto3" json:"import1,omitempty"`
	Import2   float64                `protobuf:"fixed64,3,opt,name=import2,proto3" json:"import2,omitempty"`
	Export1   float64                `protobuf:"fixed64,4,opt,name=export1,proto3" json:"export1,omitempty"`
	Export2   float64                `protobuf:"fixed64,5,opt,name=export2,proto3" json:"export2,omitempty"`
	Net       float64                `protobuf:"fixed64,6,opt,name=net,proto3" json:"net,omitempty"`
	Power     int64                  `protobuf:"varint,7,opt,name=power,proto3" json:"power,omitempty"`
}

func (x *MeterReadingResponse_Electricity) Reset() {
	*x = MeterReadingResponse_Electricity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeterReadingResponse_Electricity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingResponse_Electricity) ProtoMessage() {}

func (x *MeterReadingResponse_Electricity) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingResponse_Electricity.ProtoReflect.Descriptor instead.
func (*MeterReadingResponse_Electricity) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MeterReadingResponse_Electricity) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeterReadingResponse_Electricity) GetImport1() float64 {
	if x != nil {
		return x.Import1
	}
	return 0
}

func (x *MeterReadingResponse_Electricity) GetImport2() float64 {
	if x != nil {
		return x.Import2
	}
	return 0
}

func (x *MeterReadingResponse_Electricity) GetExport1() float64 {
	if x != nil {
		return x.Export1
	}
	return 0
}

func (x *MeterReadingResponse_Electricity) GetExport2() float64 {
	if x != nil {
		return x.Export2
	}
	return 0
}

func (x *MeterReadingResponse_Electricity) GetNet() float64 {
	if x != nil {
		return x.Net
	}
	return 0
}

func (x *MeterReadingResponse_Electricity) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

type MeterReadingResponse_S0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Total     float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Current   int64                  `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
}

func (x *MeterReadingResponse_S0) Reset() {
	*x = MeterReadingResponse_S0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeterReadingResponse_S0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingResponse_S0) ProtoMessage() {}

func (x *MeterReadingResponse_S0) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingResponse_S0.ProtoReflect.Descriptor instead.
func (*MeterReadingResponse_S0) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MeterReadingResponse_S0) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeterReadingResponse_S0) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MeterReadingResponse_S0) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type MeterReadingResponse_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Total     float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *MeterReadingResponse_Value) Reset() {
	*x = MeterReadingResponse_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeterReadingResponse_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterReadingResponse_Value) ProtoMessage() {}

func (x *MeterReadingResponse_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterReadingResponse_Value.ProtoReflect.Descriptor instead.
func (*MeterReadingResponse_Value) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1, 2}
}

func (x *MeterReadingResponse_Value) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeterReadingResponse_Value) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PhaseReadingResponse_Phase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current float64 `protobuf:"fixed64,1,opt,name=current,proto3" json:"current,omitempty"`
	Power   float64 `protobuf:"fixed64,2,opt,name=power,proto3" json:"power,omitempty"`
	Voltage float64 `protobuf:"fixed64,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
}

func (x *PhaseReadingResponse_Phase) Reset() {
	*x = PhaseReadingResponse_Phase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_apiv1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhaseReadingResponse_Phase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseReadingResponse_Phase) ProtoMessage() {}

func (x *PhaseReadingResponse_Phase) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseReadingResponse_Phase.ProtoReflect.Descriptor instead.
func (*PhaseReadingResponse_Phase) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PhaseReadingResponse_Phase) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PhaseReadingResponse_Phase) GetPower() float64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PhaseReadingResponse_Phase) GetVoltage() float64 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

var File_api_v1_apiv1_proto protoreflect.FileDescriptor

var file_api_v1_apiv1_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a,
	0x13, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xe3, 0x05, 0x0a, 0x14, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x0b, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0b,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x34,
	0x0a, 0x02, 0x73, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x30, 0x48, 0x01, 0x52, 0x02, 0x73,
	0x30, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x02, 0x52, 0x03, 0x67, 0x61, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x3d, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x03, 0x52, 0x05, 0x77, 0x61, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x1a, 0xd7,
	0x01, 0x0a, 0x0b, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x69, 0x74, 0x79, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6e,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x1a, 0x6e, 0x0a, 0x02, 0x53, 0x30, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x1a, 0x57, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x69, 0x74,
	0x79, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x73, 0x30, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x67, 0x61, 0x73,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x77, 0x61, 0x74, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xbb, 0x01, 0x0a, 0x14, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x12, 0x38, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x1a, 0x51, 0x0a, 0x05,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x32,
	0xa6, 0x01, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b,
	0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x65, 0x6c, 0x64, 0x65, 0x76, 0x2f, 0x79,
	0x6f, 0x75, 0x6c, 0x65, 0x73, 0x73, 0x2d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_apiv1_proto_rawDescOnce sync.Once
	file_api_v1_apiv1_proto_rawDescData = file_api_v1_apiv1_proto_rawDesc
)

func file_api_v1_apiv1_proto_rawDescGZIP() []byte {
	file_api_v1_apiv1_proto_rawDescOnce.Do(func() {
		file_api_v1_apiv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_apiv1_proto_rawDescData)
	})
	return file_api_v1_apiv1_proto_rawDescData
}

var file_api_v1_apiv1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_apiv1_proto_goTypes = []interface{}{
	(*MeterReadingRequest)(nil),              // 0: api.v1.MeterReadingRequest
	(*MeterReadingResponse)(nil),             // 1: api.v1.MeterReadingResponse
	(*PhaseReadingRequest)(nil),              // 2: api.v1.PhaseReadingRequest
	(*PhaseReadingResponse)(nil),             // 3: api.v1.PhaseReadingResponse
	(*MeterReadingResponse_Electricity)(nil), // 4: api.v1.MeterReadingResponse.Electricity
	(*MeterReadingResponse_S0)(nil),          // 5: api.v1.MeterReadingResponse.S0
	(*MeterReadingResponse_Value)(nil),       // 6: api.v1.MeterReadingResponse.Value
	(*PhaseReadingResponse_Phase)(nil),       // 7: api.v1.PhaseReadingResponse.Phase
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
}
var file_api_v1_apiv1_proto_depIdxs = []int32{
	4,  // 0: api.v1.MeterReadingResponse.electricity:type_name -> api.v1.MeterReadingResponse.Electricity
	5,  // 1: api.v1.MeterReadingResponse.s0:type_name -> api.v1.MeterReadingResponse.S0
	6,  // 2: api.v1.MeterReadingResponse.gas:type_name -> api.v1.MeterReadingResponse.Value
	6,  // 3: api.v1.MeterReadingResponse.water:type_name -> api.v1.MeterReadingResponse.Value
	7,  // 4: api.v1.PhaseReadingResponse.phase:type_name -> api.v1.PhaseReadingResponse.Phase
	8,  // 5: api.v1.MeterReadingResponse.Electricity.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 6: api.v1.MeterReadingResponse.S0.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 7: api.v1.MeterReadingResponse.Value.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: api.v1.APIService.MeterReading:input_type -> api.v1.MeterReadingRequest
	2,  // 9: api.v1.APIService.PhaseReading:input_type -> api.v1.PhaseReadingRequest
	1,  // 10: api.v1.APIService.MeterReading:output_type -> api.v1.MeterReadingResponse
	3,  // 11: api.v1.APIService.PhaseReading:output_type -> api.v1.PhaseReadingResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_apiv1_proto_init() }
func file_api_v1_apiv1_proto_init() {
	if File_api_v1_apiv1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_apiv1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeterReadingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeterReadingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseReadingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseReadingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeterReadingResponse_Electricity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeterReadingResponse_S0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeterReadingResponse_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_apiv1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhaseReadingResponse_Phase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_apiv1_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_apiv1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_apiv1_proto_goTypes,
		DependencyIndexes: file_api_v1_apiv1_proto_depIdxs,
		MessageInfos:      file_api_v1_apiv1_proto_msgTypes,
	}.Build()
	File_api_v1_apiv1_proto = out.File
	file_api_v1_apiv1_proto_rawDesc = nil
	file_api_v1_apiv1_proto_goTypes = nil
	file_api_v1_apiv1_proto_depIdxs = nil
}
