apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observer.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "observer.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "observer.labels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.observer.image.repository }}:{{ .Values.observer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.observer.image.pullPolicy }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.observer.server.port }}

          readinessProbe:
            {{- if .Values.observer.server.tls.enabled }}
            {{- if .Values.observer.server.tls.verifyClient }}
            exec:
              command: [ /main, healthcheck ]
            {{- else }}
            httpGet:
              path: /healthy
              port: http
              scheme: HTTPS
            {{- end }}
            {{- else }}
            httpGet:
              path: /healthy
              port: http
            {{- end }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            {{- if .Values.observer.server.tls.enabled }}
            {{- if .Values.observer.server.tls.verifyClient }}
            exec:
              command: [ /main, healthcheck ]
            {{- else }}
            httpGet:
              path: /healthy
              port: http
              scheme: HTTPS
            {{- end }}
            {{- else }}
            httpGet:
              path: /healthy
              port: http
            {{- end }}

          env:
            - name: LOG_LEVEL
              value: {{ .Values.observer.debug | ternary "debug" .Values.observer.log.level | quote }}
            - name: LOG_TIMESTAMP
              value: {{ .Values.observer.log.timestamp | quote }}
            - name: SERVER_ACCESS_LOG
              value: {{ .Values.observer.debug | ternary "true" .Values.observer.log.accessLog | quote }}
            {{- if .Values.observer.server }}
            - name: SERVER_PORT
              value: {{ .Values.observer.server.port | quote }}
            {{- if and .Values.observer.server.tls .Values.observer.server.tls.enabled }}
            - name: SERVER_TLS_VERIFY_CLIENT
              value: {{ .Values.observer.server.tls.verifyClient | quote }}
            - name: SERVER_TLS_INSECURE_SKIP_VERIFY
              value: {{ .Values.observer.debug | ternary "true" .Values.observer.server.tls.insecureSkipVerify | quote }}
            {{- if .Values.observer.server.tls.caSecretName }}
            - name: SERVER_TLS_CA_CERT_FILE
              value: "/mnt/server-tls-ca/ca.crt"
            {{- else if .Values.observer.server.tls.caCertFile }}
            - name: SERVER_TLS_CA_CERT_FILE
              value: {{ .Values.observer.server.tls.caCertFile | quote }}
            {{- end }}
            {{- if .Values.observer.server.tls.secretName }}
            - name: SERVER_TLS_CERT_FILE
              value: "/mnt/server-tls/tls.crt"
            - name: SERVER_TLS_KEY_FILE
              value: "/mnt/server-tls/tls.key"
            {{- else }}
            - name: SERVER_TLS_CERT_FILE
              value: {{ .Values.observer.server.tls.certFile | quote }}
            - name: SERVER_TLS_KEY_FILE
              value: {{ .Values.observer.server.tls.keyFile | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.observer.otel }}
            {{- if .Values.observer.otel.serviceName }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.observer.otel.serviceName | quote }}
            {{- else }}
            - name: OTEL_SERVICE_NAME
              value: {{ include "observer.fullname" . | quote }}
            {{- end }}
            {{- if .Values.observer.otel.resourceAttributes }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.observer.otel.resourceAttributes | quote }}
            {{- end }}
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: {{ .Values.observer.otel.metric.exportInterval | quote }}
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              value: {{ .Values.observer.otel.metric.exportTimeout | quote }}
            {{- if and .Values.observer.otel.traces .Values.observer.otel.traces.enabled }}
            - name: OTEL_TRACES_ENABLED
              value: "true"
            - name: OTEL_TRACES_SAMPLER
              value: {{ .Values.observer.otel.traces.sampler | quote }}
            - name: OTEL_TRACES_SAMPLER_ARG
              value: {{ .Values.observer.otel.traces.samplerArg | quote }}
            {{- end }}
            {{- if .Values.observer.otel.exporter }}
            {{- if and .Values.observer.otel.exporter.otlp .Values.observer.otel.exporter.otlp.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.observer.otel.exporter.otlp.endpoint | quote }}
            {{- if .Values.observer.otel.exporter.otlp.headers }}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: {{ .Values.observer.otel.exporter.otlp.headers | quote }}
            {{- end }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.observer.otel.exporter.otlp.protocol | quote }}
            - name: OTEL_EXPORTER_OTLP_TIMEOUT
              value: {{ .Values.observer.otel.exporter.otlp.timeout | quote }}
            {{- if and .Values.observer.otel.exporter.otlp.tls .Values.observer.otel.exporter.otlp.tls.enabled }}
            {{- if .Values.observer.otel.exporter.otlp.tls.caSecretName }}
            - name: OTEL_EXPORTER_OTLP_CERTIFICATE
              value: "/mnt/otlp-tls-ca/ca.crt"
            {{- else if .Values.observer.otel.exporter.otlp.tls.caCertFile }}
            - name: OTEL_EXPORTER_OTLP_CERTIFICATE
              value: {{ .Values.observer.otel.exporter.otlp.tls.caCertFile | quote }}
            {{- end }}
            {{- if .Values.observer.otel.exporter.otlp.tls.secretName }}
            - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
              value: "/mnt/otlp-client-tls/tls.crt"
            - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
              value: "/mnt/otlp-client-tls/tls.key"
            {{- else }}
            - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
              value: {{ .Values.observer.otel.exporter.otlp.tls.certFile | quote }}
            - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
              value: {{ .Values.observer.otel.exporter.otlp.tls.keyFile | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.observer.youless }}
            {{- if .Values.observer.youless.configMapName }}
            - name: YOULESS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.observer.youless.configMapName | quote }}
                  key: url
            - name: YOULESS_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.observer.youless.configMapName | quote }}
                  key: name
            - name: YOULESS_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.observer.youless.configMapName | quote }}
                  key: timeout
                  optional: true
            {{- else }}
            - name: YOULESS_BASE_URL
              value: {{ .Values.observer.youless.url | quote }}
            - name: YOULESS_NAME
              value: {{ .Values.observer.youless.name | quote }}
            - name: YOULESS_TIMEOUT
              value: {{ .Values.observer.youless.timeout | quote }}
            {{- end }}
            {{- if .Values.observer.youless.secretName }}
            - name: YOULESS_PASSWORD_FILE
              value: "/mnt/youless-password/password"
            {{- else if .Values.observer.youless.configMapName }}
            - name: YOULESS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.observer.youless.configMapName | quote }}
                  key: password
                  optional: true
            {{- else if .Values.observer.youless.password }}
            - name: YOULESS_PASSWORD
              value: {{ .Values.observer.youless.password | quote }}
            {{- end }}
            {{- end }}
            - name: OBSERVER_EXCLUDE_POWER
              value: {{ .Values.observer.excludePower | quote }}
            - name: OBSERVER_EXCLUDE_S0
              value: {{ .Values.observer.excludeS0 | quote }}
            - name: OBSERVER_EXCLUDE_GAS
              value: {{ .Values.observer.excludeGas | quote }}
            - name: OBSERVER_EXCLUDE_WATER
              value: {{ .Values.observer.excludeWater | quote }}
            - name: OBSERVER_SINGLE_PHASE
              value: {{ .Values.observer.singlePhase | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            {{- if and .Values.observer.server .Values.observer.server.tls .Values.observer.server.tls.enabled }}
            {{- if .Values.observer.server.tls.secretName }}
            - name: server-tls
              mountPath: /mnt/server-tls
              readOnly: true
            {{- end }}
            {{- if .Values.observer.server.tls.caSecretName }}
            - name: server-tls-ca
              mountPath: /mnt/server-tls-ca
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if and .Values.observer.otel .Values.observer.otel.exporter .Values.observer.otel.exporter.otlp }}
            {{- if and .Values.observer.otel.exporter.otlp.tls .Values.observer.otel.exporter.otlp.tls.enabled }}
            {{- if .Values.observer.otel.exporter.otlp.tls.secretName }}
            - name: otlp-client-tls
              mountPath: /mnt/otlp-client-tls
              readOnly: true
            {{- end }}
            {{- if .Values.observer.otel.exporter.otlp.tls.caSecretName }}
            - name: otlp-tls-ca
              mountPath: /mnt/otlp-tls-ca
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if and  .Values.observer.youless .Values.observer.youless.secretName }}
            - name: youless-password
              mountPath: /mnt/youless-password
              readOnly: true
            {{- end }}

      volumes:
        {{- if and .Values.observer.server .Values.observer.server.tls .Values.observer.server.tls.enabled }}
        {{- if .Values.observer.server.tls.secretName }}
        - name: server-tls
          secret:
            secretName: {{ .Values.observer.server.tls.secretName }}
            defaultMode: 288 # 0400
        {{- end }}
        {{- if .Values.observer.server.tls.caSecretName }}
        - name: server-tls-ca
          secret:
            secretName: {{ .Values.observer.server.tls.caSecretName }}
            defaultMode: 288 # 0400
        {{- end }}
        {{- end }}
        {{- if and .Values.observer.otel .Values.observer.otel.exporter .Values.observer.otel.exporter.otlp }}
        {{- if and .Values.observer.otel.exporter.otlp.tls .Values.observer.otel.exporter.otlp.tls.enabled }}
        {{- if .Values.observer.otel.exporter.otlp.tls.secretName }}
        - name: otlp-client-tls
          secret:
            secretName: {{ .Values.observer.otel.exporter.otlp.tls.secretName }}
            defaultMode: 288 # 0400
        {{- end }}
        {{- if .Values.observer.otel.exporter.otlp.tls.caSecretName }}
        - name: otlp-tls-ca
          secret:
            secretName: {{ .Values.observer.otel.exporter.otlp.tls.caSecretName }}
            defaultMode: 288 # 0400
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if and .Values.observer.youless .Values.observer.youless.secretName }}
        - name: youless-password
          secret:
            secretName: {{ .Values.observer.youless.secretName }}
            defaultMode: 288 # 0400
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
