{{- if .Values.networkPolicy }}
{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "observer.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      {{- include "observer.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
      - port: 2512
        protocol: TCP
{{- end }}
{{- end }}
