// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/apiv1.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/roeldev/youless-observer/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// APIServiceName is the fully-qualified name of the APIService service.
	APIServiceName = "api.v1.APIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// APIServiceMeterReadingProcedure is the fully-qualified name of the APIService's MeterReading RPC.
	APIServiceMeterReadingProcedure = "/api.v1.APIService/MeterReading"
	// APIServicePhaseReadingProcedure is the fully-qualified name of the APIService's PhaseReading RPC.
	APIServicePhaseReadingProcedure = "/api.v1.APIService/PhaseReading"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	aPIServiceServiceDescriptor            = v1.File_api_v1_apiv1_proto.Services().ByName("APIService")
	aPIServiceMeterReadingMethodDescriptor = aPIServiceServiceDescriptor.Methods().ByName("MeterReading")
	aPIServicePhaseReadingMethodDescriptor = aPIServiceServiceDescriptor.Methods().ByName("PhaseReading")
)

// APIServiceClient is a client for the api.v1.APIService service.
type APIServiceClient interface {
	MeterReading(context.Context, *connect.Request[v1.MeterReadingRequest]) (*connect.Response[v1.MeterReadingResponse], error)
	PhaseReading(context.Context, *connect.Request[v1.PhaseReadingRequest]) (*connect.Response[v1.PhaseReadingResponse], error)
}

// NewAPIServiceClient constructs a client for the api.v1.APIService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAPIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) APIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &aPIServiceClient{
		meterReading: connect.NewClient[v1.MeterReadingRequest, v1.MeterReadingResponse](
			httpClient,
			baseURL+APIServiceMeterReadingProcedure,
			connect.WithSchema(aPIServiceMeterReadingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		phaseReading: connect.NewClient[v1.PhaseReadingRequest, v1.PhaseReadingResponse](
			httpClient,
			baseURL+APIServicePhaseReadingProcedure,
			connect.WithSchema(aPIServicePhaseReadingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// aPIServiceClient implements APIServiceClient.
type aPIServiceClient struct {
	meterReading *connect.Client[v1.MeterReadingRequest, v1.MeterReadingResponse]
	phaseReading *connect.Client[v1.PhaseReadingRequest, v1.PhaseReadingResponse]
}

// MeterReading calls api.v1.APIService.MeterReading.
func (c *aPIServiceClient) MeterReading(ctx context.Context, req *connect.Request[v1.MeterReadingRequest]) (*connect.Response[v1.MeterReadingResponse], error) {
	return c.meterReading.CallUnary(ctx, req)
}

// PhaseReading calls api.v1.APIService.PhaseReading.
func (c *aPIServiceClient) PhaseReading(ctx context.Context, req *connect.Request[v1.PhaseReadingRequest]) (*connect.Response[v1.PhaseReadingResponse], error) {
	return c.phaseReading.CallUnary(ctx, req)
}

// APIServiceHandler is an implementation of the api.v1.APIService service.
type APIServiceHandler interface {
	MeterReading(context.Context, *connect.Request[v1.MeterReadingRequest]) (*connect.Response[v1.MeterReadingResponse], error)
	PhaseReading(context.Context, *connect.Request[v1.PhaseReadingRequest]) (*connect.Response[v1.PhaseReadingResponse], error)
}

// NewAPIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAPIServiceHandler(svc APIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aPIServiceMeterReadingHandler := connect.NewUnaryHandler(
		APIServiceMeterReadingProcedure,
		svc.MeterReading,
		connect.WithSchema(aPIServiceMeterReadingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServicePhaseReadingHandler := connect.NewUnaryHandler(
		APIServicePhaseReadingProcedure,
		svc.PhaseReading,
		connect.WithSchema(aPIServicePhaseReadingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.APIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case APIServiceMeterReadingProcedure:
			aPIServiceMeterReadingHandler.ServeHTTP(w, r)
		case APIServicePhaseReadingProcedure:
			aPIServicePhaseReadingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAPIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAPIServiceHandler struct{}

func (UnimplementedAPIServiceHandler) MeterReading(context.Context, *connect.Request[v1.MeterReadingRequest]) (*connect.Response[v1.MeterReadingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.MeterReading is not implemented"))
}

func (UnimplementedAPIServiceHandler) PhaseReading(context.Context, *connect.Request[v1.PhaseReadingRequest]) (*connect.Response[v1.PhaseReadingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.PhaseReading is not implemented"))
}
