name: publish-charts
on:
  release:
    types: [ created ]
    branches:
      - main

jobs:
  publish-charts:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Strip v from version tag
        run: |
          tag=$GITHUB_REF_NAME
          echo "VERSION=${tag:1}" >> "$GITHUB_ENV"
          echo "::notice title=VERSION::${{ env.VERSION }}"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Create chart package
        shell: bash
        run: |
          task chart:pack
          mv youless-observer-${{ env.VERSION }}.tgz charts.tgz
          cp -f charts.tgz ${{ runner.temp }}/charts.tgz

      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: Upload to release
        id: upload-to-release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: charts.tgz
          overwrite: true
          draft: true

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Update index.yaml
        run: |
          cp -f ${{ runner.temp }}/charts.tgz .
          helm repo index --url https://github.com/roeldev/youless-observer/releases/download/$GITHUB_REF_NAME --merge index.yaml .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.yaml
          git commit --signoff -m "Update index.yaml"
          git push
