name: publish-release
on:
  release:
    types: [ published ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Strip v from version tag
        run: |
          tag=$GITHUB_REF_NAME
          echo "VERSION=${tag:1}" >> "$GITHUB_ENV"
          echo "::notice title=VERSION::${{ env.VERSION }}"

      - uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          pull: true
          push: true
          tags: roeldev/youless-observer:${{ env.VERSION }}

      - name: Get latest release info
        id: get_latest
        run: |
          apt-get install jq \
          latest=$(curl -s "https://api.github.com/repos/roeldev/youless-observer/releases/latest" | jq '.tag_name') \
          echo "LATEST=$latest" >> "$GITHUB_ENV"

      - name: Tag as latest
        if: ${{ env.LATEST == github.ref_name }}
        run: |
          docker tag roeldev/youless-observer:${{ env.VERSION }} roeldev/youless-observer:latest
          docker push roeldev/youless-observer:latest
