name: release-experimental
on:
  push:
    branches: [main]
    paths-ignore:
      - '.run/**'
      - 'charts/**'
      - '.*'
      - 'README.md'
      - 'Taskfile.*'

jobs:
  release-experimental:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2

      - uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and push Docker image
        run: task experimental
